executables:
  test:
    main: Test
    main-is: Test.hs
    source-dirs: src
    ghc-options: -Wall -O2
library:
  source-dirs: src
  exposed-modules:
    - NioForm
    - NioFormM
    - NioFormInstances
    - NioFormTypes
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.14
- transformers
- bytestring
- split
- text
- string-conversions
- HUnit
- tasty
- tasty-hunit
name: niobiumcoconut
version: '0.3.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
