executables:
  test:
    main: Test
    source-dirs: src
    ghc-options: -Wall -O2
library:
  source-dirs: src
  #exposed-modules:
    #- NioForm
    #- NioFormInstances
    #- NioFieldErrorInstances
    #- NioFormTypes
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base 
- transformers
- bytestring
- split
- text
- string-conversions
- HUnit
- tasty
- tasty-hunit
- mtl
- pretty-simple
name: niobiumcoconut
version: '0.7.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
