library:
  source-dirs: src
  exposed-modules:
    - NioForm
    - NioFormInstances
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.14
# common
# - lens
#- aeson
- bytestring
#- stm
- split
- text
# - time
# - thyme
# - binary
# - binary-orphans
# - old-locale
# - directory
# - pretty-simple
- string-conversions
name: niobiumcoconut
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
